CREATE DATABASE EMPLOYEE_TRACKER;

USE EMPLOYEE_TRACKER;

CREATE TABLE EMPLOYEE (
  `ID` INT  AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(30) NULL,
  `LAST_NAME` VARCHAR(30) NULL,
  `ROLE_ID` INT NULL,
  `MANAGER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE ROLE (
  `ID` INT  AUTO_INCREMENT,
  `TITLE` VARCHAR(30) NOT NULL,
  `SALARY` DECIMAL(10,4) NULL,
  `DEPARTMENT_ID` INT NULL,
  `EMPLOYEE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ROLE_EMPLOYEE1_idx` (`EMPLOYEE_ID` ASC),
  CONSTRAINT `fk_ROLE_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_ID`)
    REFERENCES `EMPLOYEE_TRACKER_DB`.`EMPLOYEE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE DEPARTMENT (
  `ID` INT  AUTO_INCREMENT,
  `NAME` VARCHAR(30) NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_DEPARTMENT_ROLE_idx` (`ROLE_ID` ASC),
  CONSTRAINT `fk_DEPARTMENT_ROLE`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `EMPLOYEE_TRACKER_DB`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)